
Process is terminated due to StackOverflowException.
